# sparse - a simple parser
# (c) 2023 by Andreas Schwenk <mailto:contact@compiler-construction.com>
# License: GPL-3.0-or-later

name: sparse
description: Simple and configurable PEG parser generator by Andreas Schwenk.
version: 0.0.1
repository: https://github.com/andreas-schwenk/sparse

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  slex: ^0.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
